### PR TITLE
Add support for implicit `$@`

### LINKED ISSUE #29: Support implicit `"$@"` in for loops
Stumbled on this one when converting some bigger POSIX scripts.

For now, the workaround is to always declare `in "$@"` explicitly.

Seems fairly doable, will try giving it a go at it later myself.

---

### Description

A for loop that omits the `$@` special var will result in error, such as:

```shell
for cmd # Implicit `in "$@"`
do
    echo "$cmd"
done
```

This is used sometimes for brevity in both scripts and functions, as well when manually setting the pseudo-array:

```shell
set -- one two three

for i
do
    echo $i
done
```

The standard covers this, as can be seen in [POSIX.1-2017: §2.9.4.2 — The for Loop](https://pubs.opengroup.org/onlinepubs/9799919799/utilities/V3_chap02.html#tag_19_09_04_03).

`babelfish`'s output could be the same as if `in "$@"` was declared explicitly:
```fish
for cmd in $argv
  echo "$cmd"
end
```

### AST error log

```go
*syntax.ForClause {
.  ForPos: 1:1
.  DoPos: 2:1
.  DonePos: 4:1
.  Select: false
.  Braces: false
.  Loop: *syntax.WordIter {
.  .  Name: *syntax.Lit {
.  .  .  ValuePos: 1:5
.  .  .  ValueEnd: 1:8
.  .  .  Value: "cmd"
.  .  }
.  .  InPos: 0:0
.  .  Items: []*syntax.Word (len = 0) {}
.  }
.  Do: []*syntax.Stmt (len = 1) {
.  .  0: *syntax.Stmt {
.  .  .  Comments: []syntax.Comment (len = 0) {}
.  .  .  Cmd: *syntax.CallExpr {
.  .  .  .  Assigns: []*syntax.Assign (len = 0) {}
.  .  .  .  Args: []*syntax.Word (len = 2) {
.  .  .  .  .  0: *syntax.Word {
.  .  .  .  .  .  Parts: []syntax.WordPart (len = 1) {
.  .  .  .  .  .  .  0: *syntax.Lit {
.  .  .  .  .  .  .  .  ValuePos: 3:2
.  .  .  .  .  .  .  .  ValueEnd: 3:6
.  .  .  .  .  .  .  .  Value: "echo"
.  .  .  .  .  .  .  }
.  .  .  .  .  .  }
.  .  .  .  .  }
.  .  .  .  .  1: *syntax.Word {
.  .  .  .  .  .  Parts: []syntax.WordPart (len = 1) {
.  .  .  .  .  .  .  0: *syntax.ParamExp {
.  .  .  .  .  .  .  .  Dollar: 3:7
.  .  .  .  .  .  .  .  Rbrace: 0:0
.  .  .  .  .  .  .  .  Short: true
.  .  .  .  .  .  .  .  Excl: false
.  .  .  .  .  .  .  .  Length: false
.  .  .  .  .  .  .  .  Width: false
.  .  .  .  .  .  .  .  Param: *syntax.Lit {
.  .  .  .  .  .  .  .  .  ValuePos: 3:8
.  .  .  .  .  .  .  .  .  ValueEnd: 3:11
.  .  .  .  .  .  .  .  .  Value: "cmd"
.  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  .  Index: nil
.  .  .  .  .  .  .  .  Slice: nil
.  .  .  .  .  .  .  .  Repl: nil
.  .  .  .  .  .  .  .  Names: 0x0
.  .  .  .  .  .  .  .  Exp: nil
.  .  .  .  .  .  .  }
.  .  .  .  .  .  }
.  .  .  .  .  }
.  .  .  .  }
.  .  .  }
.  .  .  Position: 3:2
.  .  .  Semicolon: 0:0
.  .  .  Negated: false
.  .  .  Background: false
.  .  .  Coprocess: false
.  .  .  Redirs: []*syntax.Redirect (len = 0) {}
.  .  }
.  }
.  DoLast: []syntax.Comment (len = 0) {}
}
```

### PR DESCRIPTION
**Pull request by Neved4**
Fixes #29 

You might want to add tests for this one 🚀

### CODE REVIEW

**Comment by JoaoCostaIFG** [comment]
Hi!
I believe we don't want to quote `$argv` in the resulting fish code. For example, when executing the following script with the arguments 1 2 3 we get a number per line.

```sh
for cmd; do
  echo "${cmd}"
done
```

The fish snippet:

```fish
for cmd in "$argv"
  echo "$cmd"
end
```

Will put all numbers in a single line because it only runs once (it converts the argument list into a single string).

**Comment by Neved4** [comment]
Thx a lot @JoaoCostaIFG, you're 100% right!

Just pushed another commit, cheers.

**Comment by Neved4** [comment]
Would also appreciate any guidance for tests on this one!

**Comment by bouk** [comment]
Cool, please add some tests indeed. Adding a test that has the examples in your issue would be a good start

**Comment by bouk** [comment]
Nice, thanks!

**Pull request merged**
